### ISSUE TITLE
[Bubblegum96] test_topi_conv2d_hwcn.py failed for mismatching tolerance

### ISSUE THREAD

**Issue by JammyZhou** [JammyZhou/nnvm-tvm-cl#1]
Traceback (most recent call last):
  File "test_topi_conv2d_hwcn.py", line 68, in <module>
    test_conv2d_hwcn()
  File "test_topi_conv2d_hwcn.py", line 57, in test_conv2d_hwcn
    verify_conv2d_hwcn(1, 256, 32, 256, 3, 1, "SAME")
  File "test_topi_conv2d_hwcn.py", line 53, in verify_conv2d_hwcn
    check_device(device)
  File "test_topi_conv2d_hwcn.py", line 49, in check_device
    np.testing.assert_allclose(b.asnumpy(), b_np, rtol=1e-5)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 1395, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 778, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-05, atol=0

(mismatch 100.0%)
 x: array([[[[ 247.98703 ],
         [ 246.387192],
         [ 248.895813],...
 y: array([[[[ 247.992201],
         [ 246.392194],
         [ 248.900793],...

**Comment by JammyZhou** [comment]
This unit test can pass if change the tolerance rtol from 1e-05 to 1e-04.

**Comment by pjppp** [comment]
Or you can try to set CPU FP rounding mode to round toward zero.
