### ISSUE TITLE
[Bubblegum96] test_topi_conv2d_nchw.py failed for CL_OUT_OF_RESOURCES

### ISSUE THREAD

**Issue by JammyZhou** [JammyZhou/nnvm-tvm-cl#2]
Traceback (most recent call last):
  File "test_topi_conv2d_nchw.py", line 80, in <module>
    test_conv2d_nchw()
  File "test_topi_conv2d_nchw.py", line 59, in test_conv2d_nchw
    verify_conv2d_nchw(1, 3, 224, 64, 7, 2, 3)
  File "test_topi_conv2d_nchw.py", line 54, in verify_conv2d_nchw
    check_device(device)
  File "test_topi_conv2d_nchw.py", line 48, in check_device
    func1(a, w, b)
  File "/home/linaro/tvm/python/tvm/_ffi/function.py", line 128, in __call__
    return f(*args)
  File "/home/linaro/tvm/python/tvm/_ffi/_ctypes/function.py", line 183, in __call__
    ctypes.byref(ret_val), ctypes.byref(ret_tcode)))
  File "/home/linaro/tvm/python/tvm/_ffi/base.py", line 62, in check_call
    raise TVMError(py_str(_LIB.TVMGetLastError()))
tvm._ffi.base.TVMError: [04:00:40] src/codegen/llvm/llvm_module.cc:59: Check failed: ret == 0 (-1 vs. 0) [04:00:40] src/runtime/opencl/opencl_module.cc:223: Check failed: e == CL_SUCCESS OpenCL Error, code=-5: CL_OUT_OF_RESOURCES

Stack trace returned 10 entries:
[bt] (0) /home/linaro/tvm/lib/libtvm.so(_ZN4dmlc10StackTraceB5cxx11Ev+0x44) [0x7f727dbe14]
[bt] (1) /home/linaro/tvm/lib/libtvm.so(_ZN4dmlc15LogMessageFatalD1Ev+0x30) [0x7f727dc680]
[bt] (2) /home/linaro/tvm/lib/libtvm.so(_ZNK3tvm7runtime17OpenCLWrappedFuncclENS0_7TVMArgsEPNS0_11TVMRetValueEPPv+0x808) [0x7f72b7cdf8]
[bt] (3) /home/linaro/tvm/lib/libtvm.so(_ZNSt17_Function_handlerIFvN3tvm7runtime7TVMArgsEPNS1_11TVMRetValueEEZNS1_6detail17PackFuncVoidAddr_ILi4ENS1_17OpenCLWrappedFuncEEENS1_10PackedFuncET0_RKSt6vectorINS6_14ArgConvertCodeESaISC_EEEUlS2_S4_E_E9_M_invokeERKSt9_Any_dataOS2_OS4_+0xa4) [0x7f72b7d0fc]
[bt] (4) /home/linaro/tvm/lib/libtvm.so(TVMFuncCall+0x5c) [0x7f72b564e4]
[bt] (5) [0x7f79164a68]
[bt] (6) [0x7f79164338]
[bt] (7) /home/linaro/tvm/lib/libtvm.so(_ZZN3tvm7codegen14LLVMModuleNode11GetFunctionERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt10shared_ptrINS_7runtime10ModuleNodeEEENKUlNSB_7TVMArgsEPNSB_11TVMRetValueEE0_clESG_SI_+0x28) [0x7f72a23818]
[bt] (8) /home/linaro/tvm/lib/libtvm.so(_ZNSt17_Function_handlerIFvN3tvm7runtime7TVMArgsEPNS1_11TVMRetValueEEZNS0_7codegen14LLVMModuleNode11GetFunctionERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt10shared_ptrINS1_10ModuleNodeEEEUlS2_S4_E0_E9_M_invokeERKSt9_Any_dataOS2_OS4_+0x2c) [0x7f72a23a44]
[bt] (9) /home/linaro/tvm/lib/libtvm.so(TVMFuncCall+0x5c) [0x7f72b564e4]

Stack trace returned 8 entries:
[bt] (0) /home/linaro/tvm/lib/libtvm.so(_ZN4dmlc10StackTraceB5cxx11Ev+0x44) [0x7f727dbe14]
[bt] (1) /home/linaro/tvm/lib/libtvm.so(_ZN4dmlc15LogMessageFatalD1Ev+0x30) [0x7f727dc680]
[bt] (2) /home/linaro/tvm/lib/libtvm.so(_ZZN3tvm7codegen14LLVMModuleNode11GetFunctionERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt10shared_ptrINS_7runtime10ModuleNodeEEENKUlNSB_7TVMArgsEPNSB_11TVMRetValueEE0_clESG_SI_+0x164) [0x7f72a23954]
[bt] (3) /home/linaro/tvm/lib/libtvm.so(_ZNSt17_Function_handlerIFvN3tvm7runtime7TVMArgsEPNS1_11TVMRetValueEEZNS0_7codegen14LLVMModuleNode11GetFunctionERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt10shared_ptrINS1_10ModuleNodeEEEUlS2_S4_E0_E9_M_invokeERKSt9_Any_dataOS2_OS4_+0x2c) [0x7f72a23a44]
[bt] (4) /home/linaro/tvm/lib/libtvm.so(TVMFuncCall+0x5c) [0x7f72b564e4]
[bt] (5) /usr/lib/aarch64-linux-gnu/libffi.so.6(ffi_call_SYSV+0x64) [0x7f73989f98]
[bt] (6) /usr/lib/aarch64-linux-gnu/libffi.so.6(ffi_call+0xc8) [0x7f7398a960]
[bt] (7) /usr/lib/python2.7/lib-dynload/_ctypes.aarch64-linux-gnu.so(_ctypes_callproc+0x29c) [0x7f739ac29c]

terminate called after throwing an instance of 'dmlc::Error'
  what():  [04:00:40] src/runtime/workspace_pool.cc:92: Check failed: allocated_.size() == 1 (3 vs. 1) 

Stack trace returned 5 entries:
[bt] (0) /home/linaro/tvm/lib/libtvm.so(_ZN4dmlc10StackTraceB5cxx11Ev+0x44) [0x7f727dbe14]
[bt] (1) /home/linaro/tvm/lib/libtvm.so(_ZN3tvm7runtime13WorkspacePool4Pool7ReleaseE9DLContextPNS0_9DeviceAPIE+0x474) [0x7f72b64f7c]
[bt] (2) /home/linaro/tvm/lib/libtvm.so(_ZN3tvm7runtime13WorkspacePoolD1Ev+0x48) [0x7f72b63b10]
[bt] (3) /home/linaro/tvm/lib/libtvm.so(_ZN3tvm7runtime2cl17OpenCLThreadEntryD1Ev+0x18) [0x7f72b763b0]
[bt] (4) /lib/aarch64-linux-gnu/libc.so.6(__call_tls_dtors+0x44) [0x7f78f278b4]

Aborted

**Comment by pjppp** [comment]
Better to check which cl command returns the error
