### ISSUE TITLE
[Bubblegum96] test_topi_transform.py NDRANGE_KERNEL executed abnormally

### ISSUE THREAD

**Issue by JammyZhou** [JammyZhou/nnvm-tvm-cl#5]
*** NDRANGE_KERNEL executed abnormally ***
Traceback (most recent call last):
  File "test_topi_transform.py", line 192, in <module>
    test_concatenate()
  File "test_topi_transform.py", line 176, in test_concatenate
    verify_concatenate([(2,), (2,), (2,)], 0)
  File "test_topi_transform.py", line 123, in verify_concatenate
    check_device(device)
  File "test_topi_transform.py", line 120, in check_device
    np.testing.assert_allclose(out_nd.asnumpy(), out_npy)
  File "/home/linaro/tvm/python/tvm/_ffi/ndarray.py", line 217, in asnumpy
    check_call(_LIB.TVMArrayCopyToBytes(self.handle, data, nbytes))
  File "/home/linaro/tvm/python/tvm/_ffi/base.py", line 62, in check_call
    raise TVMError(py_str(_LIB.TVMGetLastError()))
tvm._ffi.base.TVMError: [04:21:14] src/runtime/opencl/opencl_device_api.cc:92: Check failed: e == CL_SUCCESS OpenCL Error, code=-14: Unknown OpenCL error code

Stack trace returned 6 entries:
[bt] (0) /home/linaro/tvm/lib/libtvm.so(_ZN4dmlc10StackTraceB5cxx11Ev+0x44) [0x7fa5902e14]
[bt] (1) /home/linaro/tvm/lib/libtvm.so(_ZN3tvm7runtime2cl15OpenCLWorkspace14CopyDataFromToEPKvmPvmm9DLContextS6_S5_+0x1088) [0x7fa5c9c2d8]
[bt] (2) /home/linaro/tvm/lib/libtvm.so(TVMArrayCopyToBytes+0x620) [0x7fa5c7c140]
[bt] (3) /usr/lib/aarch64-linux-gnu/libffi.so.6(ffi_call_SYSV+0x64) [0x7fa6ab0f98]
[bt] (4) /usr/lib/aarch64-linux-gnu/libffi.so.6(ffi_call+0xc8) [0x7fa6ab1960]
[bt] (5) /usr/lib/python2.7/lib-dynload/_ctypes.aarch64-linux-gnu.so(_ctypes_callproc+0x29c) [0x7fa6ad329c]

**Comment by sqlin** [comment]
Hi JammyZhou,
I also meet this issue for PVR GPU, do you know how to resolve it?

**Comment by pjppp** [comment]
That happens when GPU crashes, e.g., page fault on trying to access invalid address
or invalid local memory size unfortunately not detected by the compiler
